### ISSUE TITLE
Add electric bike info to the app

### ISSUE THREAD

**Issue by mpagels** [mpagels/my-stadtrad-favorites#18]
As an **user**
I need **the info if the station has also an electric bike station**
so that **I can decide, if I want save this information as well for the dashboard**

## Description
Some stations have an electric bike for rent as well. I want to add a feature, that the user can decide if the info is needed in the dashboard or not. Because the electric bike has the disadvantage that you have to return the bike to that specific station where it was rented from. Maybe the user is not interested in the electric bike info at all.

## Acceptance criteria
- [ ] when `/thing` path is rendered, the page should indicate if this is a station with an electric bike
- [ ] and should show if an electric bike is available or not
- [ ] a `button` or `checkbox` should indicate, if the user is interested in the info in the dashboard
- [ ] when the station is already saved as favorite, the information should just update
- [ ] when the station is not saved as favorite nothing happens until the user saves the station as favorite, then the info is stored

## Tasks
- [ ] check if #6 is now helpful

## Size
- medium
