### ISSUE TITLE
Add internationalization setting

### ISSUE THREAD

**Issue by mpagels** [mpagels/my-stadtrad-favorites#20]
As an **user**
I want **to change the language of the app**
so that **I can understand what the app is saying as a non german-speaker**

## Description
Right now, the app is only usable for German-speaking user. To open the app for not speaking German user, I want to add  internationalization. Right now, I'm planing to add the English language.

## Acceptance criteria
- [x] on the setting page in the `General` section, there is an option `Spracheinstellung / Language setting`
- [x] When clicked, it opens up and the user can choose `German` or `English` as app language
- [x] The info is then set, and the app is switch to the set language
- [x] The info is also saved in `localStorage`
- [x] When coming back to the app, the language setting is extracted from `localStorage` and set

## Tasks
- [x] research how to implement internationalization in react and which framework to use (1h)

## Size
- big
