### ISSUE TITLE
Show the last bike count for a specific time, the last 5 days

### ISSUE THREAD

**Issue by mpagels** [mpagels/my-stadtrad-favorites#29]
As a user
I want to be able to set a specific time
to see all available bikes in the last 5 days on this time

## Description
I noticed, that I wanted to see, how many bikes were available on a specific time the last days. So that I could easily predict is this station a good fit for me on this time. For example, when I set a time to 12 o'clock, then I want to see how many bikes were available at 12 o'clock.

<img width="1165" alt="Bildschirmfoto 2022-04-30 um 12 54 12" src="https://user-images.githubusercontent.com/54703643/166102562-d60d8253-a268-40e3-a81c-2dc5d88d09dc.png">

For easy use, I want to use the `time picker` from `MUI`. See more infos about [here](https://mui.com/x/react-date-pickers/time-picker/#time-validation).

## Acceptance criteria
- [ ] When the station is loaded, just the `History` button is shown
- [ ] when the button is clicked, it shows the `time` input field with the current time and the `Hole letzte Tage` button
- [ ] when the `time` input field is clicked, the `time input` picker is opened
- [ ] the user can choose then a new time and save it
- [ ] when saved, the time is updated in the `time` input
- [ ] when the user click the `Hole letzte Tage` button, the app gets the bike count of the time on the last 5 days and shows it as a list
- [ ] when the `History` button is clicked again, the comonents closes, everything is removed just the button is shown
- [ ] when clicked again, all the information is still there and shown again

## Tasks
- [ ] check `MUI` for `time` picker
- [ ] create `/time` route in backend with logic to get the needed data
- [ ] translate new feature to english

## Size
big

**Comment by mpagels** [comment]
Notes: 

https://iot.hamburg.de/v1.0/Datastreams(50)/Observations?$top=2&$select=phenomenonTime,result&$orderby=phenomenonTime+desc

https://iot.hamburg.de/v1.0/Datastreams(50)/Observations?$filter=year(resultTime)%20eq%202022%20and%20month(resultTime)%20eq%204%20and%20day(resultTime)%2030$select=phenomenonTime,result&$orderby=phenomenonTime+desc

2019-07-26T09:00:43.719Z


das klappt:
https://iot.hamburg.de/v1.0/Datastreams(50)/Observations?$filter=resultTime%20le%20now()%20and%20resultTime%20ge%202022-05-01T09:00:43.719Z&$select=phenomenonTime,result&$orderby=phenomenonTime+desc
