### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by mpagels** [mpagels/my-stadtrad-favorites#3]
As an **user**
I need **a settings page**
so that **where the user can save when the color should change to yellow, when a count of bikes is less than saved numer**

## Description (Text, Scribble, Wireframe, Design)

![grafik](https://user-images.githubusercontent.com/54703643/132071605-04b62cc5-a550-418c-86d5-84b4f4798d2c.png)

The user should be able to save a number from 1 to 5 where the number indicates, when the number of available bikes should change color to yellow.

The setting page should show also some additional information of this project

"Coded with ❤ for Hamburg"
This project is open source. For bug report, contributing and feature requests, please visit the GitHub page.

Design by Sören Stein.

## Acceptance criteria

- [x] a text should state what the user can save here "Ab wie viele Fährräder soll eine Warnung (gelbe Nummer) angezeigt werden?
- [x] when there is no setting, the squares are not blue filled
- [x] When clicked/touched on a number/square the number should change to a white color and the background to blue (just the one that was clicked)
- [x] the setting for this setting should automatically been set
- [x] to disable the setting the user can click on a square with an big X on it. Then everything should reset and no setting is set

## Tasks

- [x] create & add design to story
- [x] is React context the correct way to go for the setting save? Research 30min for that

## Size

(medium)
